### ISSUE TITLE
Brute-force attacks

### ISSUE THREAD

**Issue by mquandalle** [efounders/meteor-accounts-passwordless#1]
First of all thank you for this package, I know some other developers (namely @kentonv from sandstorm) are also interested in a “passwordless” authentication for meteor applications.

Currently it seems that you aren't implementing anything to prevent brute-force attacks. Since the pass-code that is being sent by email has a very low entropy (it's a 4-digits string), brute-forcing it is trivial:

``` js
var tries = 0;
(function tryLogin(err, res) {
  if (!err) return; // No error, we are logged in!
  Meteor.loginWithPasswordless({ 
    selector: 'mquandalle',
    code: ('0000' + (tries++).toString()).slice(-4) 
  }, tryLogin);
})('start');
```

_Tested, and it works._

One possibility would be to invalidate the code after _n_ unsuccessful tries. But that basically don't solve the problem because the attacker could just re-generate a new code and try _n_ more times until he is successful. You could probably block the IP but (1) you'll have false positives (people that are blocked but didn't try to attack you) and (2) some attackers have a lot of IPs (botnets networks, or IPv6 ranges).

One other possibility would be to generate high-entropy one time password using for instance `Random.secret()` that have 256 bits of entropy which make brute-forcing strategies impossible to work, the drawback here being that if you receive the code on your mobile phone and want to input it on your computer you have to read and write a complex 43 chars string, which is super inconvenient.

**Comment by peernohell** [comment]
Hello @mquandalle,
I just commit a fix to add a delay if user tries to brute force many time. 
https://github.com/efounders/meteor-accounts-passwordless/commit/756a9c67c79990b41e018f0065dcffda17ca2bbe + plus a fix on next commit to not upsert nbTry.
