### ISSUE TITLE
URL Params

### ISSUE THREAD

**Issue by brandonmikeska** [efounders/meteor-accounts-passwordless#2]
Are you up for, or ok with adding an option to allow the user to simply click a link that had the code in it. So they could either click a link, or copy the code over?

**Comment by acemtp** [comment]
Hi,

We already have something like that. We'll push it in the package soon.

Thanks for the feedback!

**Comment by brandonmikeska** [comment]
No problem! Can't wait to see the new package.

**Comment by peernohell** [comment]
@brandonmikeska I juste add instruction in the readme https://github.com/efounders/meteor-accounts-passwordless#set-a-link-in-the-email 
Don't hesitate to comeback to me if anythings is not clear or didn't work.
