### ISSUE TITLE
Customizing some things

### ISSUE THREAD

**Issue by brandonmikeska** [efounders/meteor-accounts-passwordless#3]
Hey I am new to meteor and just didn't know best practices. I am trying to prototype a site we did in Rails, so we already have the structure in place for the collections, and didn't know if I could customize this package. Examples being changing the name of the collection, and saving more options when creating a user.

Is it best to use your package and somehow add to it, or is it best to just do my own? This probably isn't the best place to ask either, but I have no idea where else to ask it.

**Comment by acemtp** [comment]
hi, I think you should start with a classic account package, for example accounts-password to prototype your project, and if it works, it'll be easier to add accounts-passwordless
